import { ReactComponent as ArrowSouthSvg } from './assets/arrow-s.svg';
import { ReactComponent as ChevronRightSvg } from './assets/chevron-r.svg';
import { ReactComponent as CloseSvg } from './assets/close.svg';
import { ReactComponent as DocsSvg } from './assets/docs.svg';
import { ReactComponent as FooterDiscordSvg } from './assets/footer-discord.svg';
import { ReactComponent as FooterGithubSvg } from './assets/footer-github.svg';
import { ReactComponent as FooterMediumSvg } from './assets/footer-medium.svg';
import { ReactComponent as FooterTelegramSvg } from './assets/footer-telegram.svg';
import { ReactComponent as FooterTwitterSvg } from './assets/footer-twitter.svg';
import { ReactComponent as MenuSvg } from './assets/menu.svg';
import { ReactComponent as ModeSvg } from './assets/mode.svg';
import { ReactComponent as PlusSvg } from './assets/plus.svg';
import { ReactComponent as SearchSvg } from './assets/search.svg';
import { ReactComponent as SendSvg } from './assets/send.svg';
import { ReactComponent as TerraSvg } from './assets/terra.svg';
import { ReactComponent as WalletSvg } from './assets/wallet.svg';
import { ReactComponent as WalletconnectSvg } from './assets/walletconnect.svg';
import { ReactComponent as ClaimSvg } from './assets/claim.svg';
import { ReactComponent as CircleExclamationSvg } from './assets/circle-exclamation.svg';
import { createMaterialIcon } from './createMaterialIcon';

export const DocsIcon = createMaterialIcon(DocsSvg);
export const ModeIcon = createMaterialIcon(ModeSvg);
export const WalletIcon = createMaterialIcon(WalletSvg);
export const ChevronRightIcon = createMaterialIcon(ChevronRightSvg);
export const TerraIcon = createMaterialIcon(TerraSvg);
export const WalletconnectIcon = createMaterialIcon(WalletconnectSvg);
export const MenuIcon = createMaterialIcon(MenuSvg);
export const CloseIcon = createMaterialIcon(CloseSvg);
export const SearchIcon = createMaterialIcon(SearchSvg);
export const ArrowSouthIcon = createMaterialIcon(ArrowSouthSvg);
export const PlusIcon = createMaterialIcon(PlusSvg);
export const SendIcon = createMaterialIcon(SendSvg);
export const FooterMediumIcon = createMaterialIcon(FooterMediumSvg);
export const FooterDiscordIcon = createMaterialIcon(FooterDiscordSvg);
export const FooterTelegramIcon = createMaterialIcon(FooterTelegramSvg);
export const FooterTwitterIcon = createMaterialIcon(FooterTwitterSvg);
export const FooterGithubIcon = createMaterialIcon(FooterGithubSvg);
export const CircleExclamationIcon = createMaterialIcon(CircleExclamationSvg);
export const ClaimIcon = createMaterialIcon(ClaimSvg);
