import { ReactComponent as ArrowSouthSvg } from './assets/arrow-s.svg';
import { ReactComponent as ChevronRightSvg } from './assets/chevron-r.svg';
import { ReactComponent as CloseSvg } from './assets/close.svg';
import { ReactComponent as DocsSvg } from './assets/docs.svg';
import { ReactComponent as MenuSvg } from './assets/menu.svg';
import { ReactComponent as ModeSvg } from './assets/mode.svg';
import { ReactComponent as PlusSvg } from './assets/plus.svg';
import { ReactComponent as SearchSvg } from './assets/search.svg';
import { ReactComponent as TerraSvg } from './assets/terra.svg';
import { ReactComponent as WalletSvg } from './assets/wallet.svg';
import { ReactComponent as WalletconnectSvg } from './assets/walletconnect.svg';
import { ReactComponent as SendSvg } from './assets/send.svg';
import { createMaterialIcon } from './createMaterialIcon';

export const DocsIcon = createMaterialIcon(DocsSvg);
export const ModeIcon = createMaterialIcon(ModeSvg);
export const WalletIcon = createMaterialIcon(WalletSvg);
export const ChevronRightIcon = createMaterialIcon(ChevronRightSvg);
export const TerraIcon = createMaterialIcon(TerraSvg);
export const WalletconnectIcon = createMaterialIcon(WalletconnectSvg);
export const MenuIcon = createMaterialIcon(MenuSvg);
export const CloseIcon = createMaterialIcon(CloseSvg);
export const SearchIcon = createMaterialIcon(SearchSvg);
export const ArrowSouthIcon = createMaterialIcon(ArrowSouthSvg);
export const PlusIcon = createMaterialIcon(PlusSvg);
export const SendIcon = createMaterialIcon(SendSvg);
